# Generated by Django 5.2.9 on 2025-12-18 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=100)),
                ('calories', models.FloatField()),
                ('image', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(help_text='Name of the food item', max_length=200)),
                ('calories', models.IntegerField(help_text='Calories for this food entry')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this meal was logged')),
                ('user', models.ForeignKey(help_text='Owner of this meal entry', on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal Log Entry',
                'verbose_name_plural': 'Meal Log Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
