# Generated by Django 5.2.9 on 2026-01-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_alter_foodhistory_carbs_alter_foodhistory_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('office', 'Office (Sedentary)'), ('moderate', 'Moderate'), ('athlete', 'Athlete')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('loss', 'Weight Loss'), ('maintain', 'Maintain Weight'), ('gain', 'Weight Gain')], default='maintain', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_calorie_goal',
            field=models.IntegerField(default=2200, help_text='Calculated TDEE / target'),
        ),
    ]
